# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

run:
  deadline: 5m
  issues-exit-code: 1
  tests: true

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - goimports
    - gofmt
      #- revive
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unparam
      # - depguard
    - goconst
    - gocyclo
      # - gosec
    - prealloc
    - staticcheck
  disable:
    # - fieldalignment
    # - structcheck
    # - interfacer
    # - varcheck
    # - deadcode
    # - nakedret
    # - gosimple
    # - stylecheck
    # - unused
    # - dupl
    # - gochecknoinits
    # - gochecknoglobals
    # - lll
    # - typecheck
  enable-all: false
  disable-all: true
